blueprint:
  name: Automated Shutter (Door)
  description: Open and close a Shutter in combination with a door sensor
  domain: automation
  author: Philipp Klüter
  input:
    shutter_entity:
      name: Shutter Entity
      selector:
        entity:
          filter:
            domain: cover
            device_class: shutter
    workday_morning:
      name: Workday Opening
      description: Time to open the shutter on a workday.
      default: "06:30:00"
      selector:
        time:
    holiday_morning:
      name: Holiday / Weekend Opening
      description: Time to open the shutter on a holiday / weekend..
      default: "08:30:00"
      selector:
        time:
    close_time:
      name: Closing time
      description: Time to close the shutter.
      default: "21:30:00"
      selector:
        time:
    sensor_entity:
      name: Door Sensor
      selector:
        entity:
          filter:
            domain: binary_sensor
            device_class: door

mode: restart
max_exceeded: silent

triggers:
  - id: workday_morning_trigger
    at: !input workday_morning
    trigger: time
  - id: holiday_morning_trigger
    at: !input holiday_morning
    trigger: time
  - id: sun_elevation_trigger
    entity_id:
      - sun.sun
    attribute: elevation
    below: -5
    trigger: numeric_state
  - id: night_trigger
    at: !input close_time
    trigger: time
actions:
  - choose:
      - conditions:
          - or:
              - and:
                  - condition: trigger
                    id: workday_morning_trigger
                  - condition: state
                    entity_id: binary_sensor.workday_sensor
                    state: "on"
              - and:
                  - condition: trigger
                    id:
                      - holiday_morning_trigger
                  - condition: state
                    entity_id: binary_sensor.workday_sensor
                    state: "off"
        sequence:
          - action: cover.open_cover
            target:
              entity_id: !input shutter_entity
      - conditions:
          - and:
              - condition: trigger
                id: night_trigger
              - condition: state
                entity_id: !input sensor_entity
                state: "off"
              - condition: numeric_state
                entity_id: sun.sun
                attribute: elevation
                below: -5
        sequence:
          - action: cover.close_cover
            target:
              entity_id: !input shutter_entity
      - conditions:
          - and:
              - condition: trigger
                id: sun_elevation_trigger
              - condition: state
                entity_id: !input sensor_entity
                state: "off"
              - condition: numeric_state
                entity_id: sun.sun
                attribute: elevation
                below: -5
        sequence:
          - if:
              - condition: time
                before: !input close_time
            then:
              action: cover.set_cover_position
              target:
                entity_id: !input shutter_entity
              data:
                position: 60
            else:
              - action: cover.close_cover
                target:
                  entity_id: !input shutter_entity
