blueprint:
  name: Motion-activated Light with Lux Sensor
  description: Turn on a light when motion is detected and lux is below a threshold.
  domain: automation
  author: Philipp Klüter
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          filter:
            domain: binary_sensor
            device_class: motion
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    disabled_when_on:
      name: Disabled when on
      description: 'The motion activation is disabled when one of these lights is on.'
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    lux_entity:
      name: Illuminance Sensor
      selector:
        entity:
          filter:
            domain: sensor
            device_class: illuminance
    lux_threshold:
      name: Illuminance threshold
      description: Threshold for lux.
      default: 5
      selector:
        number:
          min: 0
          max: 200
          unit_of_measurement: lux

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

triggers:
  - trigger: state
    entity_id: !input motion_entity
    from: 'off'
    to: 'on'

conditions:
  - condition: numeric_state
    entity_id: !input lux_entity
    below: 5
  - condition: state
    entity_id: !disabled_when_on
    state: 'off'

actions:
  - alias: 'Turn on the light'
    action: light.turn_on
    target: !input light_target
  - alias: 'Wait until there is no motion from device'
    wait_for_trigger:
      - trigger: state
        entity_id: !input motion_entity
        from: 'on'
        to: 'off'
  - alias: 'Wait the number of seconds that has been set'
    delay: !input no_motion_wait
  - alias: 'Turn off the light'
    action: light.turn_off
    target: !input light_target
